services:
  api:
    container_name: tracker-api
    build:
      context: $PWD/tracker-api
      dockerfile: $PWD/api.Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - $PWD/tracker-api
    environment:
      FLASK_APP: tracker
      FLASK_DEBUG: "true"
      DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres
    depends_on:
      - db

  db:
    container_name: tracker-db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
