services:
  api:
    container_name: tracker-api
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/tracker-api
    environment:
      FLASK_APP: tracker
      FLASK_ENV: development
      DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres
    entrypoint: entrypoint.sh
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
